<?php
/** @var $block \Jajuma\WebpImages\Block\Picture */
$customSrcTag = $block->getCustomSrcTag();
$customSrcSetTag = $block->getCustomSrcSetTag();

$width = 1;
$height = 1;
$placeHolderUrl = 'data:image/svg+xml;base64,';

if(@($size = getimagesize($block->getOriginalImagePath())) !== false) {
    list($width, $height, $type, $attr) = $size;
}

$placeHolderSVG = '<svg xmlns="http://www.w3.org/2000/svg" width="' . $width . '" height="' . $height . '"><rect width="100%" height="100%" fill="#f1f1f1" fill-opacity="0.25" /></svg>';
$placeHolderUrl .= base64_encode($placeHolderSVG);
$originalImage = str_replace('src=', 'src="' . $placeHolderUrl . '"' . ' data-src=', $block->getOriginalTag());
?>
<?php if ($block->getMobileImage()): ?>
    <?php if ($customSrcTag): ?>
        <picture>
            <source type="image/webp" media="(max-width: 768px)" <?= $customSrcSetTag ? $customSrcSetTag : 'srcset' ?>="<?= $block->getMobileImage() ?>">
            <source type="image/webp" <?= $customSrcSetTag ? $customSrcSetTag : 'srcset' ?>="<?= $block->getWebpImage() ?>">
            <source type="<?= $block->getOriginalImageType() ?>" <?= $customSrcSetTag ? $customSrcSetTag : 'srcset' ?>="<?= $block->getOriginalImage() ?>">
            <?= $originalImage ?>
        </picture>
    <?php else: ?>
        <picture>
            <source type="image/webp" media="(max-width: 768px)" srcset="<?= $block->getMobileImage() ?>">
            <source type="image/webp" srcset="<?= $block->getWebpImage() ?>">
            <source type="<?= $block->getOriginalImageType() ?>" srcset="<?= $block->getOriginalImage() ?>">
            <?= $originalImage ?>
        </picture>
    <?php endif; ?>
<?php else: ?>
    <?php if ($customSrcTag): ?>
        <picture>
            <source type="image/webp" <?= $customSrcSetTag ? $customSrcSetTag : 'srcset' ?>="<?= $block->getWebpImage() ?>">
            <source type="<?= $block->getOriginalImageType() ?>" <?= $customSrcSetTag ? $customSrcSetTag : 'srcset' ?>="<?= $block->getOriginalImage() ?>">
            <?= $originalImage ?>
        </picture>
    <?php else: ?>
        <picture>
            <source type="image/webp" srcset="<?= $block->getWebpImage() ?>">
            <source type="<?= $block->getOriginalImageType() ?>" srcset="<?= $block->getOriginalImage() ?>">
            <?= $originalImage ?>
        </picture>
    <?php endif; ?>
<?php endif; ?>

