<?php
/**
 * Copyright (c) 2020. Volodymyr Hryvinskyi.  All rights reserved.
 * @author: <mailto:volodymyr@hryvinskyi.com>
 * @github: <https://github.com/hryvinskyi>
 */

/** @var \MageCloud\CurrencySettings\ViewModel\CurrencySettingsInterface $viewModel */
$viewModel = $block->getData('viewModel');
?>

<script>
    window.currencySettings = <?= /* @noEscape */ $viewModel->getSerializedCurrencySettings() ?>;
</script>
