<?php
/**
 * Copyright (c) 2019. Volodymyr Hryvinskyi.  All rights reserved.
 * @author: <mailto:volodymyr@hryvinskyi.com>
 * @github: <https://github.com/hryvinskyi>
 */

use Magento\Framework\App\Action\Action;

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) : ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $fontendConfig = \Magento\Framework\App\ObjectManager::getInstance()->get(\Kartbutikken\Theme\Model\Config\Catalog\Frontend::class);
    $showQuantity  = $fontendConfig->isShowQuantity();

    $showWishlist = true;
    $showCompare = false;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    ?>
    <div class="block widget block-products-list <?= /* @noEscape */ $mode ?>">
        <?php if ($block->getTitle()) : ?>
            <div class="block-title">
                <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
            </div>
        <?php endif ?>
        <div class="block-content">
            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                <ol class="product-items <?= /* @noEscape */ $type ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item) : ?>
                        <?php if (!($_item->getIsSalable())) { continue; } ?>
                        <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                        <div class="product-item-info">
                            <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                                <?php $regularPrice =  $_item->getPriceInfo()->getPrice('final_price')->getAmount()->getValue();
                                $finalPrice =  $_item->getPriceInfo()->getPrice('regular_price')->getAmount()->getValue();
                                ?>
                                <?php if ($regularPrice != $finalPrice) {
                                    $discount = $regularPrice * 100 / $finalPrice - 100;
                                    $discount =  number_format($discount, 0);
                                } ?>
                                <?php if ($regularPrice != $finalPrice) :?>
                                    <div class="discount_label">
                                        <span><?php echo $discount . '%';?></span>
                                    </div>
                                <?php endif;?>
                                <style>
                                    .discount_label {
                                        display: flex;
                                        align-items: center;
                                        justify-content: center;
                                        background: #f00;
                                        width: 45px;
                                        height: 45px;
                                        border-radius: 100%;
                                        position: absolute;
                                        bottom: 10%;
                                        left: 5%;
                                        color: #fff;
                                        font-weight: 700;
                                        z-index: 2;
                                        font-size: 12px;
                                    }
                                </style>
                                <?= $block->getImage($_item, $image)->toHtml() ?>
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                       href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-link">
                                        <?= $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>
                                <?php if ($templateType) : ?>
                                    <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>

                                <?= $block->getProductPriceHtml($_item, $type) ?>

                                <?= $block->getProductDetailsHtml($_item) ?>

                                <?php if ($showWishlist || $showCompare || $showCart) : ?>
                                    <div class="product-item-inner">
                                        <div class="product-item-actions">
                                            <?php if ($showCart) : ?>
                                                <div class="actions-primary">
                                                    <?php if ($_item->isSaleable()) : ?>
                                                        <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                        <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_item->getSku()) ?>" data-mage-init='{"catalogAddToCart":{}}' action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                                            <input type="hidden" name="product" value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                            <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                            <?= $block->getBlockHtml('formkey') ?>
                                                            <?php if ($showQuantity): ?>
                                                                <div class="box-to-cart" data-mage-init='{"qtyAddToCart":{}}'>
                                                                    <div class="control">
                                                                        <div class="qty-minus">
                                                                            <a href="javascript:void(0)" class="btn-qty minus">-</a>
                                                                        </div>
                                                                        <div class="qty-input">
                                                                            <input type="number" name="qty" title="<?= __('Qty'); ?>" value="1" class="input-text qty"></div>
                                                                        <div class="qty-plus">
                                                                            <a href="javascript:void(0)" class="btn-qty plus">+</a>
                                                                        </div>
                                                                    </div>
                                                                    <button type="submit" title="<?= __('Add to cart'); ?>" class="action tocart green">
                                                                        <span><?= __('Add to cart'); ?></span>
                                                                    </button>
                                                                </div>
                                                            <?php else: ?>
                                                                <button type="submit"
                                                                        title="<?= $block->escapeHtml(__('Add to cart')) ?>"
                                                                        class="action tocart green">
                                                                    <span><?= $block->escapeHtml(__('Add to cart')) ?></span>
                                                                </button>
                                                            <?php endif; ?>
                                                        </form>
                                                    <?php else : ?>
                                                        <?php if ($_item->getIsSalable()) : ?>
                                                            <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                        <?php else : ?>
                                                            <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                            <?php if ($showWishlist || $showCompare) : ?>
                                                <div class="actions-secondary" style="display: none" data-role="add-to-links">
                                                    <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist) : ?>
                                                        <a href="#"
                                                           data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                    <?php if ($block->getAddToCompareUrl() && $showCompare) : ?>
                                                        <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class);?>
                                                        <a href="#" class="action tocompare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>
