<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_AjaxSocialLogin
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
//  @codingStandardsIgnoreFile
?>
<?php
/**
 * @var Bss\SocialLogin\Block\SocialLogin\EnableModule $block
 */


$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$customerSession = $objectManager->get(\Magento\Customer\Model\Session::class);

$storeId = intval($storeManager->getStore()->getStoreId());
?>
<?php
if (!$block->isEnable()) {
    return;
}
if ($customerSession->isLoggedIn()) {
    return;
}
if ($storeId !== 1) {
    return;
}
?>
<form style="display:none;" class="form"
      action="<?php /* @escapeNotVerified */ echo $block->getUrl('sociallogin/account/loginPost') ?>"
      method="post"
      id="sociallogin-login-form"
>
    <input id="sociallogin-login-referer" name="refress-redirect-url" type="hidden" value="" />
    <input id="sociallogin-login-submit" type="submit" value="" />
</form>


<div id="popup_newcustomer" style="display: none">
    <div id="popup_newcustomer_content_close_btn"></div>
    <div style="display:flex;">
        <img src="/pub/media/popup.png" style="width: 50%">
        <div class="popup_newcustomer_content" style="width: 50%; padding: 10px">
            <label>Bli medlem og få 25% rabatt på ditt neste kjøp</label>
            <span>Registrer deg for å motta nyhetsbrev, så får du nyheter, tips og råd. I tillegg har vi en eksklusiv Facebook-gruppe for tur entusiaster du kan melde deg inn i.*</span>
            <div class="popup_newcustomer_content_control">
                <a id="popup_newcustomer_content_control_btn"
                   class="social-login create">Meld deg inn</a>
                <span>*Tilbudet gjelder ikke GPS-kart</span>
            </div>
        </div>
    </div>
</div>
<style>
    .popup_newcustomer {
        width: 100%;
        max-width: 100vw;
        max-height: 100vh;
        font-size: 13px;
    }
    .popup_newcustomer label {
        font-weight: 300;
        line-height: 1.1;
        font-size: 2.6rem;
        margin-top: 2.5rem;
        margin-bottom: 2rem;
        display: flex;
    }
    .popup_newcustomer  .modal-inner-wrap {
        max-width: 700px;
    }
    .popup_newcustomer .modal-footer {
        display: none;
    }
    .popup_newcustomer .modal-header {
        display: none;
    }
    .popup_newcustomer .modal-content {
        padding: 0 !important;
        text-align: center;
    }
    .popup_newcustomer_content_control {
        display: flex;
        flex-direction: column;
        justify-content: center;
        text-align: center;
        align-items: center;
        padding: 20px;
    }
    #popup_newcustomer_content_control_btn {
        color: #fff;
        background: #ff0000;
        padding: 6px 15px;
        margin-bottom: 15px;
        width: 70%;
        border-radius: 4px;
        cursor: pointer;
        font-size: 15px;
        text-decoration: none !important;
    }
    #popup_newcustomer_content_control_btn:hover {
        opacity: 0.7;
    }
    .tab-social {
        display: none;
    }
    .popup-mess-social {
        width: 100%;
        padding: 0;
    }
    .fancybox-inner {
        max-width: 100% !important;
    }
    .block-container.active .register-popup {
        display: none;
    }
    #social-form-create {
        width: 100% !important;
    }
    #social-form-create .fieldset {
        display: flex;
        flex-wrap: wrap;
        gap: 1rem;
    }
    #social-form-create .fieldset>.field {
        margin: 0;
        width: 49%;
    }
    #social-form-create .actions-toolbar {
        display: flex;
        justify-content: center;
        margin-top: 25px;
    }
    #bt-social-create {
        background: #ff0000;
        border: none;
        margin: 0 !important;
        width: 240px;
    }
    #social-login-popup .block-container {
        padding: 0 !important;
    }
    .ui-datepicker-trigger, #dob-error {
        display: none !important;
    }
    #popup_newcustomer_content_close_btn {
        position: absolute;
        right: 0;
        top: 0;
        width: 23px;
        height: 23px;
        display: flex;
        align-items: center;
        justify-content: center;
        border: 1px solid #555;
        cursor: pointer;
    }
    #popup_newcustomer_content_close_btn:hover {
   background: #ccc;
    }
    div#popup_newcustomer_content_close_btn:after {
        content: "";
        width: 12px;
        height: 2px;
        position: absolute;
        background: #000;
        transform: rotate(45deg);
    }
    div#popup_newcustomer_content_close_btn:before {
        content: "";
        width: 12px;
        height: 2px;
        position: absolute;
        background: #000;
        transform: rotate(135deg);
    }
    @media screen and (max-width: 768px){
        .popup_newcustomer .modal-inner-wrap {
            width: 75% !important;
            height: auto !important;
        }
        .popup_newcustomer img {
            display: none;
        }
        .popup_newcustomer_content {
            width: 100% !important;
        }
        .fancybox-opened {
            min-width: 300px;
        }
        #social-form-create .fieldset>.field {
            width: 100% !important;
        }
    }
</style>
<script>
require(['jquery', 'mage/cookies', 'Magento_Ui/js/modal/modal'],
    function($, cookies, modal){
$(document).ready(function(){
    if ($.mage.cookies.get('popup_newcustomer')) {
    if ($.mage.cookies.get('popup_newcustomer') === '0') {
        console.log('new customer popup closed');
}
}
else {
        console.log('new customer popup not closed');
    var options = {
        type: 'popup',
        responsive: true,
        innerScroll: false,
        modalClass: 'popup_newcustomer'
    };
    var popup = modal(options, $('#popup_newcustomer'));
    $('#popup_newcustomer').modal('openModal');

        var date = new Date();
        var days = 40;
        date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
        $.mage.cookies.set('popup_newcustomer', '0', {expires: date});

}

     $('#popup_newcustomer_content_control_btn').on('click', function(event) {
    //     var date = new Date();
    //     var days = 40;
    //     date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
         $('#popup_newcustomer').modal('closeModal');
    //     $.mage.cookies.set('popup_newcustomer', '0', {expires: date});
     });

    $('#popup_newcustomer_content_close_btn').on('click', function(event) {
        //     var date = new Date();
        //     var days = 40;
        //     date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
        $('#popup_newcustomer').modal('closeModal');
        //     $.mage.cookies.set('popup_newcustomer', '0', {expires: date});
    });

});
});
</script>