<?php
/**
 * Copyright (c) 2020. Volodymyr Hryvinskyi.  All rights reserved.
 * @author: <mailto:volodymyr@hryvinskyi.com>
 * @github: <https://github.com/hryvinskyi>
 */

/**
 * @var \MageCloud\WeltPixelOwlCarouselSlider\Block\Slider\Custom $this
 * @var \MageCloud\WeltPixelOwlCarouselSlider\Block\Slider\Custom $block
 * @var \MageCloud\WeltPixelOwlCarouselSlider\ViewModel\OwlConfig $owlConfigViewModel
 * @var \MageCloud\WeltPixelOwlCarouselSlider\ViewModel\SwiperConfig $swiperConfigViewModel
 */

$owlConfigViewModel = $block->getOwlConfigViewModel();
$swiperConfigViewModel = $block->getSwiperConfigViewModel();

$sliderConfig  = $this->getSliderConfiguration();
$sliderGeneral = $sliderConfig['slider_config'];
$enabled       = (array_key_exists('status', $sliderGeneral) && $sliderGeneral['status'] !=0) ? true : false;
$thumbsEnabled = (array_key_exists('thumbs', $sliderGeneral) && $sliderGeneral['thumbs'] !=0) ? true : false;
$thumbsArrow = (array_key_exists('thumbs', $sliderGeneral) && $sliderGeneral['nav'] !=0) ? true : false;
$autoPlayTime = $sliderGeneral['autoplayTimeout'];
$thumbsArr      = [];
if ($enabled) :
$sliderId     = $this->getData('slider_id');
$breakpoint   = $this->getBreakpointConfiguration();
$bannerConfig = $sliderConfig['banner_config'];
$marginBanner = $sliderGeneral['margin'];
$mediaUrl     = $this->getMediaUrl();
$isGatEnabled = $this->isGatEnabled();
$isLazyLoad   = !!$sliderGeneral['lazyLoad'];
$imageAdjustmentRequired = false;
?>

<?php if ($sliderGeneral['show_title'] && trim($sliderGeneral['title'])) : ?>
    <div class="content-heading">
        <h2 class="title"><?php echo $sliderGeneral['title']; ?></h2>
    </div>
<?php endif; ?>

<div class="custom-slider">
    <!-- Slider main container -->
    <div class="swiper-container carousel-custom-<?php echo $sliderId;?>"
     data-slider-id="<?php echo $sliderId;?>"
     data-lazy-mage-init='{"swiperWidget":<?php echo json_encode($swiperConfigViewModel->getConfig($sliderGeneral, $breakpoint)); ?>}'>
        <!-- Additional required wrapper -->
        <div class="swiper-wrapper">
            <!-- Slides -->
<?php
$ctr=0;
foreach($bannerConfig as $banner) : ?>
<?php
$title = (array_key_exists('title', $banner) && $banner['title'] !='') ? $banner['title'] : false;
$showTitle = array_key_exists('show_title', $banner) ? $banner['show_title'] : false;
$description = (array_key_exists('description', $banner) && $banner['description'] !='')
    ? $banner['description'] : false;
$showDescription = array_key_exists('show_description', $banner)
    ? $banner['show_description'] : false;
$url = array_key_exists('url', $banner) ? $banner['url'] : null;
$wrapLink = array_key_exists('wrap_link', $banner) ? $banner['wrap_link'] : false;
$target = array_key_exists('target', $banner) ? $banner['target'] : '_blank';
$bannerType = array_key_exists('banner_type', $banner) ? $banner['banner_type'] : '';
if ($bannerType == 1) {
    $imageAdjustmentRequired = true;
}
$desktopimage = array_key_exists('image', $banner) ? $banner['image'] : '';
$mobileimage = array_key_exists('mobile_image', $banner) ? $banner['mobile_image'] : '';
$thumbimage = array_key_exists('thumb_image', $banner) ? $banner['thumb_image'] : '';
if(!$desktopimage && $mobileimage) $desktopimage = $mobileimage;
if(!$thumbimage && $desktopimage) $thumbimage = $desktopimage;
$altText = array_key_exists('alt_text', $banner) ? $banner['alt_text'] : '';
$video = array_key_exists('video', $banner) ? $banner['video'] : '';
$custom = array_key_exists('custom', $banner) ? $banner['custom'] : '';
$buttonText = array_key_exists('button_text', $banner) ? $banner['button_text'] : null;
$customContent = array_key_exists('custom_content', $banner) ? $banner['custom_content'] : '';
$customCss = array_key_exists('custom_css', $banner) ? $banner['custom_css'] : '';
$gaPromoId = array_key_exists('ga_promo_id', $banner) ? $banner['ga_promo_id'] : '';
$gaPromoName = array_key_exists('ga_promo_name', $banner) ? $banner['ga_promo_name'] : '';
$gaPromoCreative = array_key_exists('ga_promo_creative', $banner) ? $banner['ga_promo_creative'] : '';
$gaPromoPosition = array_key_exists('ga_promo_position', $banner) ? $banner['ga_promo_position'] : '';
$image = $desktopimage;
$thumbsArr[$ctr]['img'] = $thumbimage;
$thumbsArr[$ctr]['alt'] = $altText;

$gaPromoPosition = array_key_exists('ga_promo_position', $banner) ? $banner['ga_promo_position'] : '';
?>

<div class="swiper-slide banner-item banner-<?php echo $banner['id']; ?>" data-swiper-autoplay="<?php echo $autoPlayTime; ?>" style="margin-right:<?php echo $marginBanner; ?>px">
<?php if ($bannerType == 1) : ?>
<?php if (!$buttonText): ?>
<?php if (isset($url)): ?>
    <a href="<?php echo $url; ?>" target="<?php echo $target; ?>"
<?php if($isGatEnabled):?>
    data-track-promo-id="<?php echo $gaPromoId; ?>"
    data-track-promo-name="<?php echo $gaPromoName; ?>"
    data-track-promo-creative="<?php echo $gaPromoCreative; ?>"
    data-track-promo-position="<?php echo $gaPromoPosition; ?>"
<?php endif;?>
>
<?php endif; ?>
<?php endif; ?>
<img <?php if (!$isLazyLoad) : ?>class="no-lazy"<?php endif; ?>
                                 src="<?php echo $mediaUrl . $image; ?>"
<?php if ($mobileimage) : ?>
    data-src-mobile="<?php echo $mediaUrl . $mobileimage ?>"
<?php if ($image) : ?>
data-src-desktop="<?php echo $mediaUrl . $desktopimage ?>"
<?php endif; ?>
<?php endif; ?>
 alt="<?php echo $altText; ?>"
 title="<?php echo $altText; ?>"
/>

<?php if (!$buttonText): ?>
<?php if (isset($url)): ?>
    </a>
<?php endif; ?>
<?php endif; ?>
<?php elseif ($bannerType == 3) : ?>
<?php if (!$buttonText): ?>
<?php if ($url): ?>
    <a href="<?php echo $url; ?>" target="<?php echo $target; ?>" >
<?php endif; ?>
<?php endif; ?>
<span class="banner-custom">
<?php echo $custom; ?>
</span>
<?php if (!$buttonText): ?>
<?php if ($url): ?>
    </a>
<?php endif; ?>
<?php endif; ?>
<?php elseif ($bannerType == 2) : ?>
    <span class="banner-video">
<?php echo $this->getVideoHtml($video);  ?>
</span>
<?php endif; ?>
<div class="content_slider">
<?php if ($showTitle && $title) : ?>
<?php if($url != NULL): ?>
    <a href="<?php echo $url; ?>" target="<?php echo $target; ?>"
<?php if($isGatEnabled):?>
    data-track-promo-id="<?php echo $gaPromoId; ?>"
    data-track-promo-name="<?php echo $gaPromoName; ?>"
    data-track-promo-creative="<?php echo $gaPromoCreative; ?>"
    data-track-promo-position="<?php echo $gaPromoPosition; ?>"
<?php endif;?>
>
<span class="banner-title"><?php echo $title; ?></span>
</a>
<?php else: ?>
    <span class="banner-title"><?php echo $title; ?></span>
<?php endif; ?>
<?php endif; ?>

<?php if ($showDescription && $description) : ?>
<?php if($url != NULL): ?>
    <a href="<?php echo $url; ?>" target="<?php echo $target; ?>"
<?php if($isGatEnabled):?>
    data-track-promo-id="<?php echo $gaPromoId; ?>"
    data-track-promo-name="<?php echo $gaPromoName; ?>"
    data-track-promo-creative="<?php echo $gaPromoCreative; ?>"
    data-track-promo-position="<?php echo $gaPromoPosition; ?>"
<?php endif;?>
>
<span class="banner-description"><?php echo $description; ?></span>
</a>
<?php else: ?>
    <span class="banner-description"><?php echo $description; ?></span>
<?php endif;?>
<?php endif; ?>

<div class="buttons">
<?php if ($customCss): ?>
    <style scoped>
<?php echo $customCss; ?>
</style>
<?php endif; ?>
<?php if ($buttonText && $url): ?>
    <a class="action primary" href="<?php echo $url; ?>" target="<?php echo $target; ?>"
<?php if($isGatEnabled):?>
    data-track-promo-id="<?php echo $gaPromoId; ?>"
    data-track-promo-name="<?php echo $gaPromoName; ?>"
    data-track-promo-creative="<?php echo $gaPromoCreative; ?>"
    data-track-promo-position="<?php echo $gaPromoPosition; ?>"
<?php endif;?>
> <?php echo $buttonText; ?> </a>
<?php endif; ?>
<?php if ($customContent): ?>
    <div class="clearfix"></div>
    <div class="custom_content">
<?php if($wrapLink && $url != NULL): ?>
    <a href="<?php echo $url; ?>" target="<?php echo $target; ?>"
<?php if($isGatEnabled):?>
    data-track-promo-id="<?php echo $gaPromoId; ?>"
    data-track-promo-name="<?php echo $gaPromoName; ?>"
    data-track-promo-creative="<?php echo $gaPromoCreative; ?>"
    data-track-promo-position="<?php echo $gaPromoPosition; ?>"
<?php endif;?>
>
<?php echo $customContent; ?>
</a>
<?php else: ?>
<?php echo $customContent; ?>
<?php endif;?>
</div>
<?php endif; ?>
</div>
</div>
</div>

<?php $ctr++; endforeach; ?>
</div>
<!-- If we need pagination -->
<div class="swiper-pagination"></div>
<!-- If we need navigation buttons -->

<?php if ($thumbsArrow) :?>
<div class="swiper-button-prev"><span aria-label="Previous">‹</span></div>
<div class="swiper-button-next"><span aria-label="Next">›</span></div>
<?php endif; ?>
</div>
</div>
<?php endif; ?>


