<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<h3><?php echo __('Sorry but we are currently updating our shop'); ?></h3>
<h3><?php echo __('Vi beklager men butikken er under oppdatering.'); ?></h3>
<h3><?php echo __('Entschuldigung, aber wir aktualisieren gerade unseren Shop'); ?></h3>
<p>
    <?php //echo __('The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.'); ?>
</p>
<style>
    header {
        display: none;
    }
</style>