<?php
/**
 * Copyright (c) 2020. Volodymyr Hryvinskyi.  All rights reserved.
 * @author: <mailto:volodymyr@hryvinskyi.com>
 * @github: <https://github.com/hryvinskyi>
 */

/** @var \Magento\ConfigurableProduct\Pricing\Render\FinalPriceBox$block */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
?>
<?php if (!$block->isProductList() && $block->hasSpecialPrice()) : ?>
    <span class="old-price sly-old-price no-display">
        <?= /* @noEscape */ $block->renderAmount($priceModel->getAmount(), [
            'display_label'     => '',
            'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
            'price_type'        => 'oldPrice',
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
    </span>
<?php endif; ?>
<span class="normal-price">
    <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
        'display_label' => '',
        'price_id' => $block->getPriceId('product-price-' . $idSuffix),
        'price_type' => 'finalPrice',
        'include_container' => true,
        'schema' => $schema,
    ]); ?>
</span>

<?php if (!$block->isProductList() && $block->hasSpecialPrice()) : ?>
    <?php
    $pricingHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');
    $oldPrice = (float)$priceModel->getValue();
    $finalPrice = (float)$finalPriceModel->getValue();
    $save = (float)$oldPrice - (float)$finalPrice;
    $saving = number_format($save, 0, '.', '');
    $savePercent = 100 - round(($finalPrice / $oldPrice) * 100);
    $savePercent =  number_format($savePercent, 0);

    ?>
    <div class="save-price sly-old-price no-display" data-price-amount="<?php echo $saving ?>" id="<?php echo $block->getPriceId('save-price-' . $idSuffix) ?>">
        <?php echo __('<span>Your discount is %1 (%2)</span>', $pricingHelper->currency($saving, true, false), $savePercent . '%'); ?>
    </div>
<?php endif; ?>


<?php if ($block->showMinimalPrice()) : ?>
    <?php if ($block->getUseLinkForAsLowAs()) :?>
        <a href="<?= $block->escapeUrl($block->getSaleableItem()->getProductUrl()) ?>" class="minimal-price-link">
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        </a>
    <?php else :?>
        <span class="minimal-price-link">
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        </span>
    <?php endif?>
<?php endif; ?>
