<?php
/**
 * Copyright (c) 2019. Volodymyr Hryvinskyi.  All rights reserved.
 * @author: <mailto:volodymyr@hryvinskyi.com>
 * @github: <https://github.com/hryvinskyi>
 */

/**
 * @var $block \Magento\Catalog\Block\Product\View\AbstractView
 */
$_product = $block->getProduct();
?>
<?php if ($block->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable()): ?>
        <div class="stock available" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
            <i class="icon-box-open" style="color:#45B348;"></i>
            <span itemprop="availability"><?= $block->escapeHtml(__('In stock')) ?></span>
        </div>
    <?php else: ?>
        <div class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
            <i class="icon-box-open" style="color: #B24545"></i>
            <span itemprop="availability"><?= $block->escapeHtml(__('Out of stock')) ?></span>
        </div>
    <?php endif; ?>
<?php endif; ?>
