<?php
/**
 * Copyright (c) 2017. Volodumur Hryvinskyi.  All rights reserved.
 * @author: <mailto:volodumur@hryvinskyi.com>
 * @github: <https://github.com/scriptua>
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */

use Hryvinskyi\Base\Helper\Html;
?>
<div class="btn-go-to-product">
    <?php echo Html::a('<span>' . __('Go To Product') . '</span>', $block->getProduct()->getProductUrl(), [
        'target' => '_blank',
        'title' => __('Go To Product'),
        'class' => ['action', 'yellow']
    ]); ?>
</div>
