<?php
/**
 * Copyright (c) 2019. Volodymyr Hryvinskyi.  All rights reserved.
 * @author: <mailto:volodymyr@hryvinskyi.com>
 * @github: <https://github.com/hryvinskyi>
 */

/** @var $block Magento\Framework\View\Element\Template */
?>
<div class="panel-button-compare" data-bind="scope: 'compareProducts'" data-role="compare-products-link">
    <a class="action compare no-display" title="<?= $block->escapeHtmlAttr(__('Compare Products')) ?>"
       data-bind="attr: {'href': compareProducts().listUrl}, css: {'no-display': !compareProducts().count}">
        <div class="panel-button-icon"><i class="icon-heart"></i></div>
        <div class="panel-button-label"><span><?= $block->escapeHtml(__('Compare Products')) ?></span></div>
        <span class="counter qty" data-bind="text: compareProducts().countCaption"></span>
    </a>
</div>
<script type="text/x-magento-init">
{"[data-role=compare-products-link]":{"Magento_Ui/js/core/app":<?= /* @noEscape */ $block->getJsLayout() ?>}}
</script>
