<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_Gallery
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile

/**
 * Block
 *
 * @var $block \Bss\Gallery\Block\CategoryView
 */
$category = $block->getCategory();
$items = $block->getCollection();
$isAutoLoad = $block->isAutoLoad();
$pageSpeed = $block->getPageSpeed();
$titlePosition = $block->getTitlePosition();
$transitionEffect = $block->getTransitionEffect();
$layout = $this->getData('bss_gallery_layout');
?>
<div id="gallery-wrapper">
    <?php if ($items && $items->getSize() > 0) : ?>
        <?php
        $sliderSpeed = $this->getData('bss_gallery_slider_autoplay_timeout');
        if ($sliderSpeed == '') {
            $sliderSpeed = $pageSpeed;
        }
        ?>
        <?php if (!$block->disableFancybox()) : ?>
    <link rel="stylesheet" type="text/css"
          href="<?= $block->escapeUrl($block->getViewFileUrl('Bss_Gallery::js/fancybox/source/jquery.fancybox.css')) ?>">
    <?php endif; ?>

        <h2 class="gallery-category-item-title"><?= $block->escapeHtml($this->getData('bss_gallery_description')); ?></h2>
    <?php if ($layout == 'standard') : ?>
        <ul class="gallery-category-list-widget gallery-item-list-widget">
            <?php foreach ($items as $item): ?>
                <li class="gallery-category-list-item-widget">
                    <div class="gallery-category-item-widget">
                        <?php if ($item->getVideo() != null) : ?>
                            <a title="<?= $block->escapeHtml($item->getDescription()) ?>"
                               href="<?= $block->escapeUrl($item->getVideo()) ?>"
                               data-caption="<?= $block->escapeHtml($item->getDescription()) ?>"
                               class="fancybox-widget fancybox.iframe.widget" rel="gallery"
                               style="text-align: center">
                                <img src="<?= $block->escapeUrl($block->getImageResize($item->getImage(), 'item')) ?>"/>
                                <span style="display: block;font-size: 16px;color: #333;padding: 5px 15px 5px;"><?= $block->escapeHtml($item->getDescription()) ?></span>
                            </a>
                        <?php else : ?>
                            <a title="<?= $block->escapeHtml($item->getDescription()) ?>"
                               href="<?= $block->escapeUrl($block->getBaseUrl() . $item->getLink()) ?>"
                               data-caption="<?= $block->escapeHtml($item->getDescription()) ?>"
                               style="text-align: center">
                                <img src="<?= $block->escapeUrl($block->getImageResize($item->getImage(), 'item')) ?>"/>
                                <span style="display: block;font-size: 16px;color: #333;padding: 5px 15px 5px;"><?= $block->escapeHtml($item->getDescription()) ?></span>
                            </a>
                        <?php endif ?>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
        <script type="text/x-magento-init">
                {
                    "*": {
                            "Bss_Gallery/js/gallery_click_standard":{
                            "isAutoLoad" : <?= $block->escapeHtml($isAutoLoad); ?>,
                            "pageSpeed" : <?= $block->escapeHtml($pageSpeed); ?>,
                            "nextEffect": "<?= $block->escapeHtml($transitionEffect); ?>",
                            "titlePosition": "<?= $block->escapeHtml($titlePosition); ?>"
                        }
                    }
                }
            </script>
    <?php endif; ?>
    <?php if ($layout == 'slider') : ?>
        <ul class="gallery_slider owl-carousel">
            <?php foreach ($items as $item) : ?>
                <li class="item">
                    <div class="gallery-category-item-widget">
                        <?php if ($item->getVideo() != null) : ?>
                            <a title="<?= $block->escapeHtml($item->getDescription()) ?>"
                               href="<?= $block->escapeUrl($item->getVideo()) ?>"
                               data-caption="<?= $block->escapeHtml($item->getDescription()) ?>"
                               class="fancybox-widget fancybox.iframe.widget" rel="gallery">
                                <img height="300" width="300"
                                     src="<?= $block->escapeUrl($block->getImageResize($item->getImage(), 'item')) ?>"/>
                            </a>
                        <?php else : ?>
                            <a title="<?= $block->escapeHtml($item->getDescription()) ?>"
                               href="<?= $block->escapeUrl($block->getBaseUrl() . $item->getLink()) ?>"
                               data-caption="<?= $block->escapeHtml($item->getDescription()) ?>">
                                <img height="300" width="300"
                                     src="<?= $block->escapeUrl($block->getImageResize($item->getImage(), 'item')) ?>"/>
                            </a>
                        <?php endif; ?>
                    </div>
                    <h4 class="gallery-category-item-title">
                        <?= $block->escapeHtml($item->getTitle()) ?>
                    </h4>
                </li>
            <?php endforeach; ?>
        </ul>
        <div id="popup-modal" style="display:none;"></div>
        <script type="text/x-magento-init">
                {
                    "*": {
                            "Bss_Gallery/js/gallery_click":{
                            "isAutoLoad" : <?= $block->escapeHtml($isAutoLoad) ?>,
                            "pageSpeed" : <?= $block->escapeHtml($pageSpeed) ?>,
                            "nextEffect": "<?= $block->escapeHtml($transitionEffect) ?>",
                            "titlePosition": "<?= $block->escapeHtml($titlePosition) ?>"
                        }
                    }
                }
            </script>
        <script type="text/x-magento-init">
                {
                    "*": {
                            "Bss_Gallery/js/gallery":{
                            "getAutoPlay" : <?= $block->escapeHtml($this->getData('bss_gallery_slider_autoplay')); ?>,
                            "timeOut" : "<?= $block->escapeHtml($sliderSpeed); ?>"
                        }
                    }
                }
            </script>
    <?php endif; ?>
    <?php else : ?>
        <p><?= $block->escapeHtml(__('This Category has no image !')) ?></p>
    <?php endif; ?>
</div>
<?php if ($titlePosition == 'inside') : ?>
    <style>
        .fancybox-slide--current .fancybox-content {
            background: white !important;
        }
        .fancybox-slide--current .fancybox-content .fancybox-image {
            padding: 30px !important;
        }
        .fancybox-slide--current .fancybox-content .fancybox-caption__body {
            color:black !important;
        }
        .fancybox-slide--current .fancybox-content .fancybox-caption.fancybox-caption--separate {
            height: 50px !important;
            background:unset !important;
            display:block !important;
        }
    </style>
<?php elseif ($titlePosition == 'over') : ?>
    <style>
        .fancybox-slide--current .fancybox-content .fancybox-caption.fancybox-caption--separate {
            position: inherit !important;
            background: unset !important;
            display:block !important;
        }
        .fancybox-slide--current .fancybox-content .fancybox-caption.fancybox-caption--separate .fancybox-caption__body {
            position:absolute !important;
            left:0px !important;
            bottom:0px !important;
            color:white !important;
            background-color:black !important;
        }
    </style>
<?php endif; ?>
