<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Theme\Block\Html\Header\CriticalCss $criticalCssViewModel
 */
?>

<link rel="dns-prefetch" href="https://www.googletagmanager.com/">
<link rel="preconnect" href="https://www.googletagmanager.com/" crossorigin>

<link rel="dns-prefetch" href="https://bam.nr-data.net/">
<link rel="preconnect" href="https://bam.nr-data.net/" crossorigin>

<link rel="dns-prefetch" href="https://www.google-analytics.com/">
<link rel="preconnect" href="https://www.google-analytics.com/" crossorigin>

<link rel="dns-prefetch" href="https://stats.g.doubleclick.net/">
<link rel="preconnect" href="https://stats.g.doubleclick.net/" crossorigin>